services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 33routes_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start