services:
  33routes_postgres:
    container_name: 33routes_postgres
    image: postgis/postgis:17-3.5-alpine
    env_file: 
      - .env
    volumes:
      - ./database/postgres/init:/docker-entrypoint-initdb.d
      - ./database/postgres/data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - 33routes_backend_network
        
  33routes_redis:
    container_name: 33routes_redis
    image: redis:7-alpine
    volumes:
      - ./database/redis/data:/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - 33routes_backend_network

networks:
  33routes_backend_network:
    external: true