http:
  middlewares:
    cors:
      headers:
        accessControlAllowOriginList:
          - "http://localhost:3000"
          - "http://localhost:8081"
        accessControlAllowCredentials: true
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
