[package]
name = "image_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["full"] }
axum = "0.7.7"
axum-server = "0.7.1"
tower-http = { version = "0.6.1", features = ["cors"] }
