FROM rust:1.82.0 AS builder

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y musl-tools ca-certificates

RUN rustup target add x86_64-unknown-linux-musl

COPY . .

RUN cargo build --release --target x86_64-unknown-linux-musl

FROM scratch

COPY --from=builder /usr/src/app/target/x86_64-unknown-linux-musl/release/image_service /usr/local/bin/image_service

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

CMD ["image_service"]
