FROM golang:1.22-alpine AS builder

WORKDIR /usr/src/app

RUN apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /auth_service ./src

FROM scratch

COPY --from=builder /auth_service /auth_service

CMD ["/auth_service"]

