FROM golang:1.22 AS builder

WORKDIR /usr/src/app

COPY . .

RUN go mod tidy
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /auth_service ./src

FROM scratch

COPY --from=builder /auth_service /auth_service

CMD ["/auth_service"]
